import type { DesignSpec, GeneratedFile, GeneratedProject, ScanReport } from "@nn/shared";
import { deriveSiteData, type SiteData } from "./derive";
import { cssVariables } from "./tokens";

const esc = (s: string): string =>
  s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");

export function generateHtml(spec: DesignSpec, report: ScanReport): GeneratedProject {
  const site = deriveSiteData(report, spec);
  return {
    framework: "html",
    entry: "index.html",
    files: [
      file("index.html", "html", html(site)),
      file("styles.css", "css", styles(spec)),
      file("script.js", "javascript", script()),
      file("README.md", "markdown", readme(site)),
    ],
  };
}

function file(path: string, language: string, content: string): GeneratedFile {
  return { path, content: content.trimStart(), language };
}

function readme(site: SiteData): string {
  return `# ${site.name}

Generated by NN Drama. Open \`index.html\` in a browser or serve the folder:

\`\`\`bash
npx serve .
\`\`\`
`;
}

function nav(site: SiteData): string {
  return site.nav
    .map((l) => `        <a href="${l.href}">${esc(l.label)}</a>`)
    .join("\n");
}

function sectionMarkup(site: SiteData): string {
  return site.sections
    .map((s) => {
      if (s.kind === "stats") {
        const cells = s.items
          .map(
            (i) => `        <div class="stat">
          <div class="stat__value">${esc(i.title)}</div>
          <div class="stat__label">${esc(i.body)}</div>
        </div>`,
          )
          .join("\n");
        return `    <section class="band">
      <div class="container stats">
${cells}
      </div>
    </section>`;
      }
      if (s.kind === "cta") {
        return `    <section class="container">
      <div class="cta">
        <h2>${esc(s.title)}</h2>
        <p>${esc(s.body)}</p>
        <a class="btn btn--primary" href="#">Get started</a>
      </div>
    </section>`;
      }
      const cards = s.items
        .map(
          (i) => `        <article class="card">
          <h3>${esc(i.title)}</h3>
          <p>${esc(i.body)}</p>
        </article>`,
        )
        .join("\n");
      return `    <section id="${s.id}" class="container">
      <h2 class="section-title">${esc(s.title)}</h2>
      <p class="section-sub">${esc(s.body)}</p>
      <div class="grid">
${cards}
      </div>
    </section>`;
    })
    .join("\n");
}

function footerMarkup(site: SiteData): string {
  const cols = site.footer.columns
    .map(
      (c) => `      <div>
        <h4>${esc(c.title)}</h4>
        <ul>${c.links.map((l) => `<li><a href="#">${esc(l)}</a></li>`).join("")}</ul>
      </div>`,
    )
    .join("\n");
  return cols;
}

function html(site: SiteData): string {
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${esc(site.name)}</title>
    <meta name="description" content="${esc(site.description)}" />
    <link rel="stylesheet" href="styles.css" />
  </head>
  <body>
    <header class="nav">
      <div class="container nav__inner">
        <a class="brand" href="#">${esc(site.name)}</a>
        <nav class="nav__links">
${nav(site)}
        </nav>
        <a class="btn btn--primary" href="#">${esc(site.hero.cta)}</a>
      </div>
    </header>

    <main>
      <section class="container hero">
        <p class="eyebrow">${esc(site.hero.eyebrow)}</p>
        <h1>${esc(site.hero.heading)}</h1>
        <p class="hero__sub">${esc(site.hero.sub)}</p>
        <div class="hero__actions">
          <a class="btn btn--primary" href="#">${esc(site.hero.cta)}</a>
          <a class="btn btn--ghost" href="#">${esc(site.hero.secondaryCta)}</a>
        </div>
      </section>

${sectionMarkup(site)}
    </main>

    <footer class="footer">
      <div class="container footer__grid">
        <div>
          <div class="brand">${esc(site.name)}</div>
          <p>${esc(site.footer.tagline)}</p>
        </div>
${footerMarkup(site)}
      </div>
    </footer>

    <script src="script.js"></script>
  </body>
</html>
`;
}

function styles(spec: DesignSpec): string {
  return `:root {
${cssVariables(spec)}
  --radius: 10px;
}

* { box-sizing: border-box; }

body {
  margin: 0;
  background: var(--color-background, #fff);
  color: var(--color-text, #111827);
  font-family: system-ui, -apple-system, Segoe UI, Roboto, sans-serif;
  line-height: 1.6;
}

a { color: inherit; text-decoration: none; }

.container {
  max-width: var(--container, 1200px);
  margin-inline: auto;
  padding-inline: 1.5rem;
}

.nav {
  position: sticky;
  top: 0;
  z-index: 40;
  border-bottom: 1px solid var(--color-border, #e5e7eb);
  background: color-mix(in srgb, var(--color-background, #fff) 85%, transparent);
  backdrop-filter: blur(8px);
}

.nav__inner { display: flex; align-items: center; justify-content: space-between; height: 64px; }
.nav__links { display: none; gap: 1.5rem; font-size: 0.9rem; }
@media (min-width: 768px) { .nav__links { display: flex; } }
.brand { font-weight: 700; font-size: 1.1rem; }

.btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  border-radius: var(--radius);
  padding: 0.6rem 1.1rem;
  font-size: 0.9rem;
  font-weight: 500;
  border: 1px solid transparent;
  transition: opacity .15s ease;
  cursor: pointer;
}
.btn:hover { opacity: .9; }
.btn--primary { background: var(--color-primary, #6366f1); color: #fff; }
.btn--ghost { border-color: var(--color-border, #e5e7eb); }

.hero { padding: 6rem 1.5rem; text-align: center; }
.eyebrow { text-transform: uppercase; letter-spacing: .08em; font-size: .8rem; font-weight: 600; color: var(--color-primary, #6366f1); }
.hero h1 { font-size: clamp(2rem, 6vw, 3.75rem); line-height: 1.1; margin: .5rem auto 1rem; max-width: 48rem; }
.hero__sub { max-width: 34rem; margin: 0 auto; color: var(--color-muted, #6b7280); }
.hero__actions { display: flex; justify-content: center; gap: .75rem; margin-top: 2rem; }

section { padding: 5rem 0; }
.section-title { text-align: center; font-size: 2rem; margin: 0 0 .5rem; }
.section-sub { text-align: center; color: var(--color-muted, #6b7280); max-width: 34rem; margin: 0 auto 3rem; }

.grid { display: grid; gap: 1.5rem; grid-template-columns: 1fr; }
@media (min-width: 640px) { .grid { grid-template-columns: repeat(2, 1fr); } }
@media (min-width: 1024px) { .grid { grid-template-columns: repeat(3, 1fr); } }

.card {
  border: 1px solid var(--color-border, #e5e7eb);
  background: var(--color-card, #fff);
  border-radius: var(--radius);
  padding: 1.5rem;
}
.card h3 { margin: 0 0 .5rem; font-size: 1.1rem; }
.card p { margin: 0; color: var(--color-muted, #6b7280); font-size: .925rem; }

.band { border-top: 1px solid var(--color-border, #e5e7eb); border-bottom: 1px solid var(--color-border, #e5e7eb); background: var(--color-surface, #f9fafb); }
.stats { display: grid; grid-template-columns: repeat(2, 1fr); gap: 2rem; text-align: center; }
@media (min-width: 768px) { .stats { grid-template-columns: repeat(4, 1fr); } }
.stat__value { font-size: 1.75rem; font-weight: 700; color: var(--color-primary, #6366f1); }
.stat__label { color: var(--color-muted, #6b7280); font-size: .9rem; }

.cta {
  background: var(--color-primary, #6366f1);
  color: #fff;
  text-align: center;
  border-radius: var(--radius);
  padding: 4rem 2rem;
}
.cta .btn--primary { background: #fff; color: var(--color-primary, #6366f1); margin-top: 1.5rem; }

.footer { border-top: 1px solid var(--color-border, #e5e7eb); padding: 4rem 0; }
.footer__grid { display: grid; gap: 2rem; grid-template-columns: 1fr; }
@media (min-width: 768px) { .footer__grid { grid-template-columns: repeat(4, 1fr); } }
.footer h4 { font-size: .9rem; margin: 0 0 .75rem; }
.footer ul { list-style: none; margin: 0; padding: 0; color: var(--color-muted, #6b7280); font-size: .9rem; }
.footer li { margin-bottom: .5rem; }
`;
}

function script(): string {
  return `// Smooth-scroll for in-page navigation.
document.querySelectorAll('a[href^="#"]').forEach((link) => {
  link.addEventListener("click", (event) => {
    const id = link.getAttribute("href");
    if (!id || id === "#") return;
    const target = document.querySelector(id);
    if (target) {
      event.preventDefault();
      target.scrollIntoView({ behavior: "smooth" });
    }
  });
});
`;
}
