import type { DesignSpec, GeneratedFile, GeneratedProject, ScanReport } from "@nn/shared";
import { deriveSiteData, type SiteData, type SiteSection } from "./derive";
import { cssVariables, tailwindColorEntries } from "./tokens";

const q = (value: string): string => JSON.stringify(value);

export function generateNextjs(spec: DesignSpec, report: ScanReport): GeneratedProject {
  const site = deriveSiteData(report, spec);
  const files: GeneratedFile[] = [
    file("package.json", "json", packageJson(site)),
    file("README.md", "markdown", readme(site)),
    file("tsconfig.json", "json", tsconfig()),
    file("next.config.mjs", "javascript", nextConfig()),
    file("postcss.config.mjs", "javascript", postcssConfig()),
    file("tailwind.config.ts", "typescript", tailwindConfig(spec)),
    file(".env.example", "text", envExample()),
    file("src/app/layout.tsx", "tsx", layout(site)),
    file("src/app/globals.css", "css", globals(spec)),
    file("src/app/page.tsx", "tsx", page(site)),
    file("src/lib/constants.ts", "typescript", constants(site)),
    file("src/components/Button.tsx", "tsx", buttonComponent()),
    file("src/components/Card.tsx", "tsx", cardComponent()),
    file("src/components/Navbar.tsx", "tsx", navbarComponent(site)),
    file("src/components/Hero.tsx", "tsx", heroComponent(site)),
    file("src/components/Footer.tsx", "tsx", footerComponent(site)),
  ];

  const kinds = new Set(site.sections.map((s) => s.kind));
  if (kinds.has("features"))
    files.push(file("src/components/Features.tsx", "tsx", featuresComponent(site)));
  if (kinds.has("stats"))
    files.push(file("src/components/Stats.tsx", "tsx", statsComponent(site)));
  if (kinds.has("pricing"))
    files.push(file("src/components/Pricing.tsx", "tsx", pricingComponent(site)));
  if (kinds.has("testimonials"))
    files.push(
      file("src/components/Testimonials.tsx", "tsx", testimonialsComponent(site)),
    );
  if (kinds.has("cta"))
    files.push(file("src/components/CTA.tsx", "tsx", ctaComponent(site)));

  return { framework: "nextjs", entry: "src/app/page.tsx", files };
}

function file(path: string, language: string, content: string): GeneratedFile {
  return { path, content: content.trimStart(), language };
}

function packageJson(site: SiteData): string {
  return JSON.stringify(
    {
      name: slugify(site.name),
      version: "0.1.0",
      private: true,
      scripts: { dev: "next dev", build: "next build", start: "next start", lint: "next lint" },
      dependencies: { next: "15.1.6", react: "19.0.0", "react-dom": "19.0.0" },
      devDependencies: {
        "@types/node": "^22.10.0",
        "@types/react": "^19.0.0",
        "@types/react-dom": "^19.0.0",
        autoprefixer: "^10.4.20",
        postcss: "^8.4.49",
        tailwindcss: "^3.4.17",
        typescript: "^5.7.3",
      },
    },
    null,
    2,
  );
}

function readme(site: SiteData): string {
  return `# ${site.name}

Generated by NN Drama from a public website analysis.

## Getting started

\`\`\`bash
npm install
npm run dev
\`\`\`

## Notes

- Colors, spacing and the container width are defined as CSS variables in
  \`src/app/globals.css\`.
- Replace placeholder imagery and copy with your own assets. Respect the
  original site's license and trademarks.
`;
}

function tsconfig(): string {
  return JSON.stringify(
    {
      compilerOptions: {
        target: "ES2022",
        lib: ["dom", "dom.iterable", "esnext"],
        strict: true,
        noEmit: true,
        esModuleInterop: true,
        module: "esnext",
        moduleResolution: "bundler",
        resolveJsonModule: true,
        isolatedModules: true,
        jsx: "preserve",
        incremental: true,
        plugins: [{ name: "next" }],
        paths: { "@/*": ["./src/*"] },
      },
      include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
      exclude: ["node_modules"],
    },
    null,
    2,
  );
}

function nextConfig(): string {
  return `/** @type {import('next').NextConfig} */
const nextConfig = { reactStrictMode: true };
export default nextConfig;
`;
}

function postcssConfig(): string {
  return `export default { plugins: { tailwindcss: {}, autoprefixer: {} } };
`;
}

function tailwindConfig(spec: DesignSpec): string {
  return `import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
${tailwindColorEntries(spec) || '        primary: "var(--color-primary)",'}
      },
      fontFamily: {
        sans: ["var(--font-sans)", "system-ui", "sans-serif"],
      },
      maxWidth: {
        container: "var(--container)",
      },
    },
  },
  plugins: [],
};

export default config;
`;
}

function envExample(): string {
  return `# Public environment variables for the generated site
NEXT_PUBLIC_SITE_URL="http://localhost:3000"
`;
}

function layout(site: SiteData): string {
  return `import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { site } from "@/lib/constants";

export const metadata: Metadata = {
  title: ${q(site.name)},
  description: ${q(site.description)},
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
`;
}

function globals(spec: DesignSpec): string {
  return `@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
${cssVariables(spec)}
  --font-sans: system-ui, -apple-system, Segoe UI, Roboto, sans-serif;
}

html {
  scroll-behavior: smooth;
}

body {
  background: var(--color-background, #ffffff);
  color: var(--color-text, #111827);
  font-family: var(--font-sans);
  margin: 0;
}

.container-page {
  max-width: var(--container);
  margin-inline: auto;
  padding-inline: 1.5rem;
}
`;
}

function page(site: SiteData): string {
  const kinds = new Set(site.sections.map((s) => s.kind));
  const imports: string[] = [`import Hero from "@/components/Hero";`];
  if (kinds.has("features")) imports.push(`import Features from "@/components/Features";`);
  if (kinds.has("stats")) imports.push(`import Stats from "@/components/Stats";`);
  if (kinds.has("pricing")) imports.push(`import Pricing from "@/components/Pricing";`);
  if (kinds.has("testimonials"))
    imports.push(`import Testimonials from "@/components/Testimonials";`);
  if (kinds.has("cta")) imports.push(`import CTA from "@/components/CTA";`);

  const body: string[] = [];
  for (const s of site.sections) {
    body.push(`      <${componentName(s)} />`);
  }

  return `${imports.join("\n")}

export default function HomePage() {
  return (
    <>
      <Hero />
${body.join("\n")}
    </>
  );
}
`;
}

function componentName(section: SiteSection): string {
  switch (section.kind) {
    case "features":
      return "Features";
    case "stats":
      return "Stats";
    case "pricing":
      return "Pricing";
    case "testimonials":
      return "Testimonials";
    case "cta":
      return "CTA";
    default:
      return "Features";
  }
}

function constants(site: SiteData): string {
  return `export const site = ${JSON.stringify(
    {
      name: site.name,
      description: site.description,
      nav: site.nav,
      hero: site.hero,
      footer: site.footer,
    },
    null,
    2,
  )} as const;

export const sections = ${JSON.stringify(site.sections, null, 2)} as const;
`;
}

function buttonComponent(): string {
  return `type ButtonProps = React.ButtonHTMLAttributes<HTMLButtonElement> & {
  variant?: "primary" | "ghost";
};

export default function Button({ variant = "primary", className = "", ...props }: ButtonProps) {
  const base =
    "inline-flex items-center justify-center rounded-md px-5 py-2.5 text-sm font-medium transition";
  const styles =
    variant === "primary"
      ? "bg-[color:var(--color-primary)] text-white hover:opacity-90"
      : "border border-[color:var(--color-border)] text-[color:var(--color-text)] hover:bg-[color:var(--color-surface)]";
  return <button className={[base, styles, className].join(" ")} {...props} />;
}
`;
}

function cardComponent(): string {
  return `export default function Card({
  title,
  children,
}: {
  title?: string;
  children: React.ReactNode;
}) {
  return (
    <div className="rounded-lg border border-[color:var(--color-border)] bg-[color:var(--color-card)] p-6">
      {title ? <h3 className="mb-2 text-lg font-semibold">{title}</h3> : null}
      <div className="text-sm text-[color:var(--color-muted)]">{children}</div>
    </div>
  );
}
`;
}

function navbarComponent(site: SiteData): string {
  const links = site.nav
    .map((l) => `            <a href=${q(l.href)} className="hover:opacity-80">${l.label}</a>`)
    .join("\n");
  return `import { site } from "@/lib/constants";
import Button from "./Button";

export default function Navbar() {
  return (
    <header className="sticky top-0 z-40 border-b border-[color:var(--color-border)] bg-[color:var(--color-background)]/80 backdrop-blur">
      <nav className="container-page flex h-16 items-center justify-between">
        <a href="#" className="text-lg font-semibold">
          {site.name}
        </a>
        <div className="hidden items-center gap-6 text-sm md:flex">
${links}
        </div>
        <Button>{site.hero.cta}</Button>
      </nav>
    </header>
  );
}
`;
}

function heroComponent(site: SiteData): string {
  return `import { site } from "@/lib/constants";
import Button from "./Button";

export default function Hero() {
  return (
    <section className="container-page py-24 text-center">
      <p className="mb-4 text-sm font-medium uppercase tracking-wide text-[color:var(--color-primary)]">
        {site.hero.eyebrow}
      </p>
      <h1 className="mx-auto max-w-3xl text-4xl font-bold leading-tight md:text-6xl">
        {site.hero.heading}
      </h1>
      <p className="mx-auto mt-6 max-w-xl text-base text-[color:var(--color-muted)] md:text-lg">
        {site.hero.sub}
      </p>
      <div className="mt-8 flex items-center justify-center gap-3">
        <Button>{site.hero.cta}</Button>
        <Button variant="ghost">{site.hero.secondaryCta}</Button>
      </div>
    </section>
  );
}
`;
}

function footerComponent(site: SiteData): string {
  const columns = site.footer.columns
    .map(
      (col) => `          <div>
            <h4 className="mb-3 text-sm font-semibold">${col.title}</h4>
            <ul className="space-y-2 text-sm text-[color:var(--color-muted)]">
${col.links.map((l) => `              <li><a href="#" className="hover:opacity-80">${l}</a></li>`).join("\n")}
            </ul>
          </div>`,
    )
    .join("\n");
  return `import { site } from "@/lib/constants";

export default function Footer() {
  return (
    <footer id="contact" className="border-t border-[color:var(--color-border)] py-16">
      <div className="container-page grid gap-10 md:grid-cols-4">
        <div>
          <div className="text-lg font-semibold">{site.name}</div>
          <p className="mt-3 max-w-xs text-sm text-[color:var(--color-muted)]">
            {site.footer.tagline}
          </p>
        </div>
${columns}
      </div>
      <div className="container-page mt-10 text-xs text-[color:var(--color-muted)]">
        © {new Date().getFullYear()} {site.name}. All rights reserved.
      </div>
    </footer>
  );
}
`;
}

function featuresComponent(site: SiteData): string {
  const section = site.sections.find((s) => s.kind === "features")!;
  const cards = section.items
    .map(
      (item) => `        <Card title=${q(item.title)}>${item.body}</Card>`,
    )
    .join("\n");
  return `import Card from "./Card";

export default function Features() {
  return (
    <section id="features" className="container-page py-20">
      <h2 className="text-center text-3xl font-bold">${section.title}</h2>
      <p className="mx-auto mt-3 max-w-xl text-center text-[color:var(--color-muted)]">
        ${section.body}
      </p>
      <div className="mt-12 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
${cards}
      </div>
    </section>
  );
}
`;
}

function statsComponent(site: SiteData): string {
  const section = site.sections.find((s) => s.kind === "stats")!;
  const cells = section.items
    .map(
      (item) => `        <div className="text-center">
          <div className="text-3xl font-bold text-[color:var(--color-primary)]">${item.title}</div>
          <div className="mt-1 text-sm text-[color:var(--color-muted)]">${item.body}</div>
        </div>`,
    )
    .join("\n");
  return `export default function Stats() {
  return (
    <section className="border-y border-[color:var(--color-border)] bg-[color:var(--color-surface)] py-16">
      <div className="container-page grid grid-cols-2 gap-8 md:grid-cols-4">
${cells}
      </div>
    </section>
  );
}
`;
}

function pricingComponent(site: SiteData): string {
  const section = site.sections.find((s) => s.kind === "pricing")!;
  const cards = section.items
    .map(
      (item) => `        <div className="rounded-lg border border-[color:var(--color-border)] bg-[color:var(--color-card)] p-6 text-center">
          <span className="text-xs font-medium uppercase text-[color:var(--color-primary)]">${item.badge ?? ""}</span>
          <h3 className="mt-2 text-lg font-semibold">${item.title}</h3>
          <p className="mt-2 text-2xl font-bold">${item.body}</p>
        </div>`,
    )
    .join("\n");
  return `export default function Pricing() {
  return (
    <section id="pricing" className="container-page py-20">
      <h2 className="text-center text-3xl font-bold">${section.title}</h2>
      <div className="mt-12 grid gap-6 md:grid-cols-3">
${cards}
      </div>
    </section>
  );
}
`;
}

function testimonialsComponent(site: SiteData): string {
  const section = site.sections.find((s) => s.kind === "testimonials")!;
  const cards = section.items
    .map(
      (item) => `        <figure className="rounded-lg border border-[color:var(--color-border)] bg-[color:var(--color-card)] p-6">
          <blockquote className="text-sm text-[color:var(--color-muted)]">${item.body}</blockquote>
          <figcaption className="mt-4 text-sm font-semibold">${item.title}</figcaption>
        </figure>`,
    )
    .join("\n");
  return `export default function Testimonials() {
  return (
    <section id="testimonials" className="container-page py-20">
      <h2 className="text-center text-3xl font-bold">${section.title}</h2>
      <div className="mt-12 grid gap-6 md:grid-cols-3">
${cards}
      </div>
    </section>
  );
}
`;
}

function ctaComponent(site: SiteData): string {
  const section = site.sections.find((s) => s.kind === "cta")!;
  return `import Button from "./Button";

export default function CTA() {
  return (
    <section className="container-page py-20">
      <div className="rounded-lg bg-[color:var(--color-primary)] px-8 py-16 text-center text-white">
        <h2 className="text-3xl font-bold">${section.title}</h2>
        <p className="mx-auto mt-3 max-w-xl opacity-90">${section.body}</p>
        <div className="mt-8">
          <Button className="bg-white text-[color:var(--color-primary)]">
            Get started
          </Button>
        </div>
      </div>
    </section>
  );
}
`;
}

function slugify(name: string): string {
  return (
    name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "") || "generated-site"
  );
}
