import type { DesignSpec, GeneratedFile, GeneratedProject, ScanReport } from "@nn/shared";
import { deriveSiteData, type SiteData } from "./derive";
import { cssVariables, tailwindColorEntries } from "./tokens";

const q = (value: string): string => JSON.stringify(value);

export function generateReact(spec: DesignSpec, report: ScanReport): GeneratedProject {
  const site = deriveSiteData(report, spec);

  const files: GeneratedFile[] = [
    file("package.json", "json", packageJson(site)),
    file("README.md", "markdown", readme(site)),
    file("tsconfig.json", "json", tsconfig()),
    file("vite.config.ts", "typescript", viteConfig()),
    file("tailwind.config.ts", "typescript", tailwindConfig(spec)),
    file("postcss.config.js", "javascript", postcssConfig()),
    file("index.html", "html", indexHtml(site)),
    file("src/main.tsx", "tsx", main()),
    file("src/App.tsx", "tsx", app(site)),
    file("src/index.css", "css", css(spec)),
    file("src/constants.ts", "typescript", constants(site)),
    file("src/components/Button.tsx", "tsx", button()),
    file("src/components/Card.tsx", "tsx", card()),
    file("src/components/Navbar.tsx", "tsx", navbar(site)),
    file("src/components/Hero.tsx", "tsx", hero(site)),
    file("src/components/Footer.tsx", "tsx", footer(site)),
    file("src/components/Sections.tsx", "tsx", sections(site)),
  ];

  return { framework: "react", entry: "src/App.tsx", files };
}

function file(path: string, language: string, content: string): GeneratedFile {
  return { path, content: content.trimStart(), language };
}

function packageJson(site: SiteData): string {
  return JSON.stringify(
    {
      name: slugify(site.name),
      version: "0.1.0",
      private: true,
      type: "module",
      scripts: { dev: "vite", build: "tsc && vite build", preview: "vite preview" },
      dependencies: { react: "19.0.0", "react-dom": "19.0.0" },
      devDependencies: {
        "@types/react": "^19.0.0",
        "@types/react-dom": "^19.0.0",
        "@vitejs/plugin-react": "^4.3.4",
        autoprefixer: "^10.4.20",
        postcss: "^8.4.49",
        tailwindcss: "^3.4.17",
        typescript: "^5.7.3",
        vite: "^6.0.7",
      },
    },
    null,
    2,
  );
}

function readme(site: SiteData): string {
  return `# ${site.name}

Generated by NN Drama.

\`\`\`bash
npm install
npm run dev
\`\`\`
`;
}

function tsconfig(): string {
  return JSON.stringify(
    {
      compilerOptions: {
        target: "ES2022",
        lib: ["DOM", "DOM.Iterable", "ES2022"],
        module: "ESNext",
        moduleResolution: "bundler",
        jsx: "react-jsx",
        strict: true,
        noEmit: true,
        esModuleInterop: true,
        skipLibCheck: true,
        resolveJsonModule: true,
      },
      include: ["src"],
    },
    null,
    2,
  );
}

function viteConfig(): string {
  return `import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

export default defineConfig({ plugins: [react()] });
`;
}

function tailwindConfig(spec: DesignSpec): string {
  return `import type { Config } from "tailwindcss";

export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
${tailwindColorEntries(spec) || '        primary: "var(--color-primary)",'}
      },
      maxWidth: { container: "var(--container)" },
    },
  },
  plugins: [],
} satisfies Config;
`;
}

function postcssConfig(): string {
  return `export default { plugins: { tailwindcss: {}, autoprefixer: {} } };
`;
}

function indexHtml(site: SiteData): string {
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${site.name}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`;
}

function main(): string {
  return `import React from "react";
import { createRoot } from "react-dom/client";
import App from "./App";
import "./index.css";

createRoot(document.getElementById("root")!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
);
`;
}

function app(site: SiteData): string {
  return `import Navbar from "./components/Navbar";
import Hero from "./components/Hero";
import Sections from "./components/Sections";
import Footer from "./components/Footer";

export default function App() {
  return (
    <>
      <Navbar />
      <main>
        <Hero />
        <Sections />
      </main>
      <Footer />
    </>
  );
}
`;
}

function css(spec: DesignSpec): string {
  return `@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
${cssVariables(spec)}
}

body {
  background: var(--color-background, #fff);
  color: var(--color-text, #111827);
  margin: 0;
  font-family: system-ui, sans-serif;
}

.container-page {
  max-width: var(--container);
  margin-inline: auto;
  padding-inline: 1.5rem;
}
`;
}

function constants(site: SiteData): string {
  return `export const site = ${JSON.stringify(site, null, 2)} as const;
`;
}

function button(): string {
  return `export default function Button({
  variant = "primary",
  className = "",
  ...props
}: React.ButtonHTMLAttributes<HTMLButtonElement> & { variant?: "primary" | "ghost" }) {
  const base = "inline-flex items-center justify-center rounded-md px-5 py-2.5 text-sm font-medium transition";
  const styles =
    variant === "primary"
      ? "bg-[color:var(--color-primary)] text-white hover:opacity-90"
      : "border border-[color:var(--color-border)] hover:bg-[color:var(--color-surface)]";
  return <button className={[base, styles, className].join(" ")} {...props} />;
}
`;
}

function card(): string {
  return `export default function Card({ title, children }: { title?: string; children: React.ReactNode }) {
  return (
    <div className="rounded-lg border border-[color:var(--color-border)] bg-[color:var(--color-card)] p-6">
      {title ? <h3 className="mb-2 text-lg font-semibold">{title}</h3> : null}
      <div className="text-sm text-[color:var(--color-muted)]">{children}</div>
    </div>
  );
}
`;
}

function navbar(site: SiteData): string {
  const links = site.nav
    .map((l) => `          <a href=${q(l.href)} className="hover:opacity-80">${l.label}</a>`)
    .join("\n");
  return `import { site } from "../constants";
import Button from "./Button";

export default function Navbar() {
  return (
    <header className="sticky top-0 z-40 border-b border-[color:var(--color-border)] bg-[color:var(--color-background)]">
      <nav className="container-page flex h-16 items-center justify-between">
        <a href="#" className="text-lg font-semibold">{site.name}</a>
        <div className="hidden items-center gap-6 text-sm md:flex">
${links}
        </div>
        <Button>{site.hero.cta}</Button>
      </nav>
    </header>
  );
}
`;
}

function hero(site: SiteData): string {
  return `import { site } from "../constants";
import Button from "./Button";

export default function Hero() {
  return (
    <section className="container-page py-24 text-center">
      <p className="mb-4 text-sm font-medium uppercase tracking-wide text-[color:var(--color-primary)]">
        {site.hero.eyebrow}
      </p>
      <h1 className="mx-auto max-w-3xl text-4xl font-bold leading-tight md:text-6xl">
        {site.hero.heading}
      </h1>
      <p className="mx-auto mt-6 max-w-xl text-[color:var(--color-muted)]">{site.hero.sub}</p>
      <div className="mt-8 flex justify-center gap-3">
        <Button>{site.hero.cta}</Button>
        <Button variant="ghost">{site.hero.secondaryCta}</Button>
      </div>
    </section>
  );
}
`;
}

function footer(site: SiteData): string {
  const columns = site.footer.columns
    .map(
      (col) => `        <div>
          <h4 className="mb-3 text-sm font-semibold">${col.title}</h4>
          <ul className="space-y-2 text-sm text-[color:var(--color-muted)]">
${col.links.map((l) => `            <li><a href="#">${l}</a></li>`).join("\n")}
          </ul>
        </div>`,
    )
    .join("\n");
  return `import { site } from "../constants";

export default function Footer() {
  return (
    <footer className="border-t border-[color:var(--color-border)] py-16">
      <div className="container-page grid gap-10 md:grid-cols-4">
        <div>
          <div className="text-lg font-semibold">{site.name}</div>
          <p className="mt-3 max-w-xs text-sm text-[color:var(--color-muted)]">{site.footer.tagline}</p>
        </div>
${columns}
      </div>
    </footer>
  );
}
`;
}

function sections(site: SiteData): string {
  const blocks = site.sections
    .map((s) => {
      if (s.kind === "stats") {
        const cells = s.items
          .map(
            (i) => `          <div className="text-center">
            <div className="text-3xl font-bold text-[color:var(--color-primary)]">${i.title}</div>
            <div className="mt-1 text-sm text-[color:var(--color-muted)]">${i.body}</div>
          </div>`,
          )
          .join("\n");
        return `      <section className="border-y border-[color:var(--color-border)] bg-[color:var(--color-surface)] py-16">
        <div className="container-page grid grid-cols-2 gap-8 md:grid-cols-4">
${cells}
        </div>
      </section>`;
      }
      if (s.kind === "cta") {
        return `      <section className="container-page py-20">
        <div className="rounded-lg bg-[color:var(--color-primary)] px-8 py-16 text-center text-white">
          <h2 className="text-3xl font-bold">${s.title}</h2>
          <p className="mx-auto mt-3 max-w-xl opacity-90">${s.body}</p>
        </div>
      </section>`;
      }
      const cards = s.items
        .map(
          (i) => `          <Card title=${q(i.title)}>${i.body}</Card>`,
        )
        .join("\n");
      return `      <section id="${s.id}" className="container-page py-20">
        <h2 className="text-center text-3xl font-bold">${s.title}</h2>
        <p className="mx-auto mt-3 max-w-xl text-center text-[color:var(--color-muted)]">${s.body}</p>
        <div className="mt-12 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
${cards}
        </div>
      </section>`;
    })
    .join("\n");

  return `import Card from "./Card";

export default function Sections() {
  return (
    <>
${blocks}
    </>
  );
}
`;
}

function slugify(name: string): string {
  return (
    name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "") || "generated-site"
  );
}
